apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: beosbank-posgres-db-europa
    tier: backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP



kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: beosbank-posgres-db-europa
    tier: backend
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432