apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-dbupdater-job
spec:
  template:
    metadata:
      name: dbupdater
    spec:
      containers:
        - name: db-updater
          image: icr.io/sgr-hackathon/flyway-migration@sha256:0140b83c02b93ccda9565d6b03fc463ea80786279ecb191a52da7b42c683524b
          volumeMounts:
            - name: sql-configmap-volume
              mountPath: /var/flyway/data/
          env:
          - name: DB_USER
            value: myhadmdq
          - name: DB_PASSWORD
            value: EO6-iHzoVwXUkBYfFlsuAYi3O5kx41X9
          - name: DB_URL
            value: "jdbc:postgresql://john.db.elephantsql.com/myhadmdq"
      restartPolicy: Never

      volumes:
      - name: sql-configmap-volume
        configMap:
          name: sql-cm
