apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: migration-task
spec:
  params:
    - name: task-pvc
      description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: cd-secret
    - name: clusterId
      description: Id of cluster
  steps:
    - name: migration-task-step
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.23
      workingDir: /artifacts
      env:
        - name: CLUSTER_ID
          value: $(params.clusterId)
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: GIT_TOKEN
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: SLACK_URL
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: API_KEY
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: DB_PASS
        - name: PIPELINE_RUN_URL
          valueFrom: 
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
        - name: TRIGGER_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-type']
        - name: TRIGGERED_BY
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by'] 
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          url="https://$GIT_TOKEN@github.com/rishi-patel1/DatabaseChangeManagement.git"
          echo "Cloning REPOSITORY"
          git clone -q $url .
          cd Pipeline/scripts
          chmod +x temp.sh
          ./temp.sh
